AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Transforms images by compression to a configured quality level
Resources:
  serverlessrepocompresstransformJL15ZU23XW5Y:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: Transforms images by compression to a configured quality level
      MemorySize: 1536
      Timeout: 300
      Role: >-
        arn:aws:iam::770328975346:role/serverlessrepo-compress-transformRole-15GRUZKRPQQ2D
      Environment:
        Variables:
          DEST_BUCKET: test-destination-bucket-compression
          QUALITY: '25'
      Tags:
        'serverlessrepo:semanticVersion': 1.0.2
        'serverlessrepo:applicationId': 'arn:aws:serverlessrepo:us-east-1:233054207705:applications/compress'
